# Generated by Django 5.1.3 on 2024-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmodelprojectbuy",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Project Buy",
                "verbose_name_plural": "historical Project Buys",
            },
        ),
        migrations.AlterModelOptions(
            name="modelprojectbuy",
            options={
                "verbose_name": "Project Buy",
                "verbose_name_plural": "Project Buys",
            },
        ),
        migrations.AddField(
            model_name="historicalmodelprojectbuy",
            name="codecoins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="modelprojectbuy",
            name="codecoins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
