# Generated by Django 5.0.7 on 2024-11-08 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="zip_file",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip", "rar", "7zip", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="zip_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip", "rar", "7zip", "webp"]
                    )
                ],
            ),
        ),
    ]
