# Generated by Django 5.0.7 on 2024-11-08 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_historicalproject_zip_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprojectlanguage",
            name="language_image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectlanguage",
            name="technology_image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectlanguage",
            name="language_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_language/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectlanguage",
            name="technology_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_technology/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
    ]
