# Generated by Django 5.0.7 on 2024-11-08 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_historicalprojectlanguage_language_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprojectbase",
            name="image",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="projectbase",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_base/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "webp"]
                    )
                ],
            ),
        ),
    ]
