# Generated by Django 5.1.3 on 2024-11-22 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustomuser",
            name="picture",
            field=models.TextField(
                blank=True,
                max_length=100,
                null=True,
                validators=[django.core.validators.validate_image_file_extension],
            ),
        ),
    ]
