# Generated by Django 5.1.4 on 2024-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("super_admin", "Super Admin"),
                    ("basic", "Basic"),
                    ("premium", "Premium"),
                ],
                default="basic",
                max_length=20,
            ),
        ),
    ]
