# Generated by Django 5.1.3 on 2024-12-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="codecoins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalcustomuser",
            name="codecoins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
