# Generated by Django 5.1.3 on 2024-11-22 05:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, max_length=1000, null=True
            ),
        ),
    ]
